*! 1.0.0 Adam Ross Nelson Jan2019 // GitHub Rebuild
*! 1.0.0 Adam Ross Nelson Aug2018 // Original Build
*! Original author : Adam Ross Nelson
*! Intended for use with datafiles generated by:
*! https://github.com/adamrossnelson/StataIPEDSAll
*! Description : Designed to reduce character length of fields with
*!               long names. Designed for use with institution names.
*!               Common words abbreviated as follows...
*!               University  -> Univ.       College     -> Col.
*!               Community   -> Comm.       State       -> St.
*!               Cosmetology -> Cosmet.     Military    -> Mil.
*!               Technical   -> Tech.       System      -> Sys.
*!               Academy     -> Acad.       Technology  -> Tech.
*!               Management  -> Mgmt.

capture program drop abbrev
program define abbrev
	
	// Version control
	version 15

	// Syntax statement requires one argument, must be variable with text type.
	syntax varlist(min=1 max=1 string) [if] [in] [, GEN(string)]
	
	
	// Tag subsample with temp var touse & test if empty.
	marksample touse, strok
	/* tab `touse'
	count if `touse'
	if `r(N)' == 0 {
		di as error "ERROR: No observations after if or in qualifier."
		error 2000
	} */
	
	clonevar `gen' = `varlist'
	replace `gen' = subinstr(`gen',"University","Univ.",.)
	replace `gen' = subinstr(`gen',"UNIVERSITY","UNIV.",.)
	
	replace `gen' = subinstr(`gen',"College","Col.",.)
	replace `gen' = subinstr(`gen',"COLLEGE","COL.",.)
	
	replace `gen' = subinstr(`gen',"Community","Comm.",.)
	replace `gen' = subinstr(`gen',"COMMUNITY","COMM.",.)
	
	replace `gen' = subinstr(`gen',"State","St.",.)
	replace `gen' = subinstr(`gen',"STATE","ST.",.)
	
	replace `gen' = subinstr(`gen',"Cosmetology","Cosmet.",.)
	replace `gen' = subinstr(`gen',"COSMETOLOGY","COSMET.",.)
	
	replace `gen' = subinstr(`gen',"Military","Mil.",.)
	replace `gen' = subinstr(`gen',"MILITARY","MIL.",.)
	
	replace `gen' = subinstr(`gen',"Technical","Tech.",.)
	replace `gen' = subinstr(`gen',"TECHNICAL","TECH.",.)
	
	replace `gen' = subinstr(`gen',"Institute","Inst.",.)
	replace `gen' = subinstr(`gen',"INSTITUTE","INST.",.)
	
	replace `gen' = subinstr(`gen',"System","Sys.",.)
	replace `gen' = subinstr(`gen',"SYSTEM","SYS.",.)
	
	replace `gen' = subinstr(`gen',"Academy","Acad.",.)
	replace `gen' = subinstr(`gen',"ACADEMY","ACAD.",.)
	
	replace `gen' = subinstr(`gen',"Technology","Tech.",.)
	replace `gen' = subinstr(`gen',"TECHNOLOGY","TECH.",.)
	
	replace `gen' = subinstr(`gen',"Management","Mgmt.",.)
	replace `gen' = subinstr(`gen',"MANAGEMENT","MGMT.",.)
	
	order `gen', after(`varlist')
	
end
