// Use this code to add indicator variables for common standard comparison groups.
// Designed for use with datafiles generated by:
//     https://github.com/adamrossnelson/StataIPEDSAll

// Jan/2018:     Adam Ross Nelson - GitHub ReBuild
// Aug/2017:     Adam Ross Nelson - Original Build

/*#############################################################################

      Maintained/more information at:
	  https://github.com/adamrossnelson/StataIPEDSAll/supp
  
##############################################################################*/

gen inNCES = 0                                    // Create indicator for NCES group.
                                                  // In 2015 it was called: "Doctoral Universities: Highest Research Activity, public/1 of 3"
replace inNCES = 1 if unitid == 104151            // Arizona State University-Tempe
replace inNCES = 1 if unitid == 104179            // University of Arizona
replace inNCES = 1 if unitid == 110635            // University of California-Berkeley
replace inNCES = 1 if unitid == 110644            // University of California-Davis
replace inNCES = 1 if unitid == 110662            // University of California-Los Angeles
replace inNCES = 1 if unitid == 132903            // University of Central Florida
replace inNCES = 1 if unitid == 133951            // Florida International University
replace inNCES = 1 if unitid == 134097            // Florida State University
replace inNCES = 1 if unitid == 134130            // University of Florida
replace inNCES = 1 if unitid == 137351            // University of South Florida-Main Campus
replace inNCES = 1 if unitid == 139959            // University of Georgia
replace inNCES = 1 if unitid == 145637            // University of Illinois at Urbana-Champaign
replace inNCES = 1 if unitid == 151351            // Indiana University-Bloomington
replace inNCES = 1 if unitid == 170976            // University of Michigan-Ann Arbor
replace inNCES = 1 if unitid == 171100            // Michigan State University
replace inNCES = 1 if unitid == 174066            // University of Minnesota-Twin Cities
replace inNCES = 1 if unitid == 186380            // Rutgers University-New Brunswick
replace inNCES = 1 if unitid == 204796            // Ohio State University-Main Campus
replace inNCES = 1 if unitid == 214777            // Pennsylvania State University-Main Campus
replace inNCES = 1 if unitid == 216339            // Temple University
replace inNCES = 1 if unitid == 225511            // University of Houston
replace inNCES = 1 if unitid == 228723            // Texas A & M University-College Station
replace inNCES = 1 if unitid == 228769            // The University of Texas at Arlington
replace inNCES = 1 if unitid == 228778            // The University of Texas at Austin
replace inNCES = 1 if unitid == 236948            // University of Washington-Seattle Campus
replace inNCES = 1 if unitid == 240444            // University of Wisconsin-Madison
replace inNCES = 1 if unitid == 243780            // Purdue University-Main Campus

gen inB10 = 0                                   // Indicator for being in Big10 Conference									
replace inB10 = 1 if unitid == 145637           // University of Illinois at Urbana-Champaign
replace inB10 = 1 if unitid == 147767           // Northwestern University
replace inB10 = 1 if unitid == 151351           // Indiana University-Bloomington
replace inB10 = 1 if unitid == 153658           // University of Iowa
replace inB10 = 1 if unitid == 163286           // University of Maryland-College Park
replace inB10 = 1 if unitid == 170976           // University of Michigan-Ann Arbor
replace inB10 = 1 if unitid == 171100           // Michigan State University
replace inB10 = 1 if unitid == 174066           // University of Minnesota-Twin Cities
replace inB10 = 1 if unitid == 181464           // University of Nebraska-Lincoln
replace inB10 = 1 if unitid == 186380           // Rutgers University-New Brunswick
replace inB10 = 1 if unitid == 204796           // Ohio State University-Main Campus
replace inB10 = 1 if unitid == 214777           // Pennsylvania State University-Main Campus
replace inB10 = 1 if unitid == 243780           // Purdue University-Main Campus
replace inB10 = 1 if unitid == 240444           // University of Wisconsin-Madison

gen inUWS = 0
replace inUWS = 1 if unitid == 240189           // University of Wisconsin-Whitewater
replace inUWS = 1 if unitid == 240268           // University of Wisconsin-Eau Claire
replace inUWS = 1 if unitid == 240277           // University of Wisconsin-Green Bay
replace inUWS = 1 if unitid == 240329           // University of Wisconsin-La Crosse
replace inUWS = 1 if unitid == 240365           // University of Wisconsin-Oshkosh
replace inUWS = 1 if unitid == 240374           // University of Wisconsin-Parkside
replace inUWS = 1 if unitid == 240417           // University of Wisconsin-Stout
replace inUWS = 1 if unitid == 240426           // University of Wisconsin-Superior
replace inUWS = 1 if unitid == 240444           // University of Wisconsin-Madison
replace inUWS = 1 if unitid == 240453           // University of Wisconsin-Milwaukee
replace inUWS = 1 if unitid == 240462           // University of Wisconsin-Platteville
replace inUWS = 1 if unitid == 240471           // University of Wisconsin-River Falls
replace inUWS = 1 if unitid == 240480           // University of Wisconsin-Stevens Point

label define uniname 999999 "Unknown"
label define uniname 104151 "Arizona State Uni-Tempe", add
label define uniname 104179 "Uni of Arizona", add
label define uniname 110635 "Uni of California-Berkeley", add
label define uniname 110644 "Uni of California-Davis", add
label define uniname 110662 "Uni of California-Los Angeles", add
label define uniname 132903 "Uni of Central Florida", add
label define uniname 133951 "Florida International Uni", add
label define uniname 134097 "Florida State Uni", add
label define uniname 134130 "Uni of Florida", add
label define uniname 137351 "Uni of South Florida", add
label define uniname 139959 "Uni of Georgia", add
label define uniname 145637 "Uni of Illinois at Urbana-Champaign", add
label define uniname 147767 "Northwestern Uni", add
label define uniname 151351 "Indiana Uni-Bloomington", add
label define uniname 153658 "Uni of Iowa", add
label define uniname 163286 "Uni of Maryland-College Park", add
label define uniname 170976 "Uni of Michigan-Ann Arbor", add
label define uniname 171100 "Michigan State Uni", add
label define uniname 174066 "Uni of Minnesota-Twin Cities", add
label define uniname 181464 "Uni of Nebraska-Lincoln", add
label define uniname 186380 "Rutgers Uni-New Brunswick", add
label define uniname 204796 "Ohio State Uni", add
label define uniname 214777 "Pennsylvania State Uni", add
label define uniname 216339 "Temple Uni", add
label define uniname 225511 "Uni of Houston", add
label define uniname 228723 "Texas A & M Uni-College Station", add
label define uniname 228769 "The Uni of Texas at Arlington", add
label define uniname 228778 "The Uni of Texas at Austin", add
label define uniname 236948 "Uni of Washington-Seattle Campus", add
label define uniname 240189 "Uni of Wisc-Whitewater", add
label define uniname 240268 "Uni of Wisc-Eau Claire", add
label define uniname 240277 "Uni of Wisc-Green Bay", add
label define uniname 240329 "Uni of Wisc-La Crosse", add
label define uniname 240365 "Uni of Wisc-Oshkosh", add
label define uniname 240374 "Uni of Wisc-Parkside", add
label define uniname 240417 "Uni of Wisc-Stout", add
label define uniname 240426 "Uni of Wisc-Superior", add
label define uniname 240444 "Uni of Wisc-Madison", add
label define uniname 240453 "Uni of Wisc-Milwaukee", add
label define uniname 240462 "Uni of Wisc-Platteville", add
label define uniname 240471 "Uni of Wisc-River Falls", add
label define uniname 240480 "Uni of Wisc-Stevens Point", add
label define uniname 243780 "Purdue Uni", add
label values unitid uniname